### ISSUE TITLE
How about Losevka and Hasklig?

### ISSUE THREAD

**Issue by FuriouslyCurious** [ProgrammingFonts/ProgrammingFonts#3]
What do you think:

https://github.com/be5invis/Iosevka

https://github.com/i-tu/Hasklig/

**Comment by ifeegoo** [comment]
Thank you @FuriouslyCurious  for your advice about the 2 good programming fonts with losevka & Hasklig,I will add these later to the project.

**Comment by FuriouslyCurious** [comment]
Thank you again for the awesome compilation!

I spent the Sunday on a programming font quest, and I think Fantasque Sans Mono might be a great addition too.  It has more curves than other mono fonts, which makes it unique.

https://github.com/belluzj/fantasque-sans

**Comment by ifeegoo** [comment]
@FuriouslyCurious Thank you for your another great advice about the Fantasque Sans Mono which looks great. 

I have already added you to the organization of @ProgrammingFonts,I strongly recommend you can fork this project and add Fantasque Sans Mono,and then do a pull request of this project.This will let you become a contributor of this project,you will be on the list of contributors.

Thank your for your concern about this project and great passion to find the great programming fonts.

This project is not good enough, and I want to build a website which can display and compare with different programming fonts with any code.But now I don't have enough time to do this because of super busy work this year and lack of front end development.

If you have interest about this ,you can join us!

**Comment by FuriouslyCurious** [comment]
Added 3 new fonts in a pull request. Thanks for the amazing repo!
